adx_enabletracking: false
adx_excludefromsearch: false
adx_hiddenfromsitemap: false
adx_name: Product image 1.png
adx_parentpageid: 2407f041-3b80-ed11-81ad-000d3a856d9f
adx_partialurl: Product image 1.png
adx_publishingstateid: 07cdd53c-3b80-ed11-81ad-000d3a85c9c7
adx_webfileid: 36cdd53c-3b80-ed11-81ad-000d3a85c9c7
annotationid: 96ded242-3b80-ed11-81ad-000d3a85c9c7
filename: Product image 1.png
isdocument: true
mimetype: image/png
objectid: 36cdd53c-3b80-ed11-81ad-000d3a85c9c7
objecttypecode: adx_webfile
